/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();
const TeamsTeamIdLazyImport = createFileRoute("/teams/$teamId")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then(d => d.Route));

const TeamsTeamIdLazyRoute = TeamsTeamIdLazyImport.update({
  id: "/teams/$teamId",
  path: "/teams/$teamId",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/teams.$teamId.lazy").then(d => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/teams/$teamId": {
      id: "/teams/$teamId";
      path: "/teams/$teamId";
      fullPath: "/teams/$teamId";
      preLoaderRoute: typeof TeamsTeamIdLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/teams/$teamId": typeof TeamsTeamIdLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/teams/$teamId": typeof TeamsTeamIdLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexLazyRoute;
  "/teams/$teamId": typeof TeamsTeamIdLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/teams/$teamId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/teams/$teamId";
  id: "__root__" | "/" | "/teams/$teamId";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  TeamsTeamIdLazyRoute: typeof TeamsTeamIdLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TeamsTeamIdLazyRoute: TeamsTeamIdLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/teams/$teamId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/teams/$teamId": {
      "filePath": "teams.$teamId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
